// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY82poA3HsGukzJ-DwA4fots45LhTfVMM',
    appId: '1:55046215845:web:d0d45e12737e5832c9154c',
    messagingSenderId: '55046215845',
    projectId: 'loginapp-menu',
    authDomain: 'loginapp-menu.firebaseapp.com',
    storageBucket: 'loginapp-menu.firebasestorage.app',
    measurementId: 'G-FB5P0R33NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL1N9fiYKWjd46gqpYEvdj1JJq4szEhk8',
    appId: '1:55046215845:android:ec85d5f150e46885c9154c',
    messagingSenderId: '55046215845',
    projectId: 'loginapp-menu',
    storageBucket: 'loginapp-menu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJWNzI-DmmQCzlt1FC8srwbGKtlZ2SxTs',
    appId: '1:55046215845:ios:2c53d9ccaa20625cc9154c',
    messagingSenderId: '55046215845',
    projectId: 'loginapp-menu',
    storageBucket: 'loginapp-menu.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );
}
